server:
  port: 8888

spring:
  cloud:
    config:
      name: configserver
      enabled: true
      server:
        git:
          uri: file://D:\MIS PROYECTOS\JAVA\microservice-configs

management:
  endpoints:
    web:
      exposure:
        include: "*"


    
  